### ISSUE TITLE
Make kitconcept.intranet distribution use the Volto Light Theme "Intranet" Header

### ISSUE THREAD

**Issue by tisto** [kitconcept/kitconcept.intranet#2]
@sneridagh do we have a config option in Volto Light Theme that allows us to switch from the standard header to the "intranet header" (see https://www.figma.com/file/eYUCbivnNrnjXjBDUizSVX/Volto-Light-Theme?type=design&node-id=998-8774&mode=design&t=4sEjZDETrva19mRK-0) that shows the search input field in the middle of the header.

![intranet-header](https://github.com/kitconcept/kitconcept.intranet/assets/632105/9e1cedfa-0f90-49bd-8fb7-ae42f26b0e58)

**Comment by steffenri** [comment]
PR: https://github.com/kitconcept/kitconcept-intranet/pull/3

**Comment by steffenri** [comment]
PR merged.
